###########################
# Configuration for rubocop
# in .rubocop.yml
# Most of these are disabling existing cops, primarily
# due to a smattering of different styles and loose
# guidlines for contributions.
#
# Any of these may be changed.

##############
# Global rules

AllCops:
  Exclude:
    - '.git/**/*'
    - 'spec/gen-ruby/**/*'
    - 'vendor/**/*'

Rails:
  Enabled: false

# Inherit default rules first, and then override those rules with our violation
# whiteelist.
inherit_from:
  - .rubocop_default.yml
  - .rubocop_todo.yml
